server:
  port: 7458

spring:
  application:
    name: armageddon-server
  profiles:
    active: default
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/armageddon?createDatabaseIfNotExist=true&setUnicode=true&characterEncoding=utf8
    username: ${MYSQL_USERNAME:username}
    password: ${MYSQL_PASSWORD:password}
  jpa:
    database-platform: org.hibernate.dialect.MySQLInnoDBDialect
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
