server:
  port: 7458

spring:
  application:
    name: armageddon-server
  profiles:
    active: default
  datasource:
    url: jdbc:mysql://localhost:3306/armageddon?setUnicode=true&characterEncoding=utf8
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
